;;; github-tags-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from github-tags.el

(autoload 'github-tags "github-tags" "\
Retrive tags data for PATH from GitHub API.

(fn PATH)")
(register-definition-prefixes "github-tags" '("github-tags-"))

;;; End of scraped data

(provide 'github-tags-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; github-tags-autoloads.el ends here
